import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";



export const metadata: Metadata = {
  title: "Product Manage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="w-full h-full container flex flex-col min-h-screen">

        <div className="navbar-section">
          <Navbar/>
        </div>
        
          <main className="flex flex-grow">
            {children}
          </main>
        
        <div className="footer-section">
          <Footer/>
        </div>

        <Toaster/>
        </div>
      </body>
    </html>
  );
}
